config/routes.rb
Rails.application.routes.draw do


  resources :activities #crates automatically when we create a scaffold where we can do CRUD for thsi table

  get 'home/index' #-> commented this line
  root 'home#index' #-> added this line to display the index.html in localhost:3000
  get 'home/about' #url for about.html.erb
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:TaskName, :Priority, :Date, :Progress, :Note)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	# the methods below are the individual webpages 
  def index
  end

  def about
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Taskname:</strong>
    <%= activity.TaskName %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= activity.Priority %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= activity.Date %>
  </p>

  <p>
    <strong>Progress:</strong>
    <%= activity.Progress %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= activity.Note %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :TaskName, style: "display: block" %>
    <%= form.text_field :TaskName %>
  </div>

  <div>
    <%= form.label :Priority, style: "display: block" %>
    <%= form.text_field :Priority %>
  </div>

  <div>
    <%= form.label :Date, style: "display: block" %>
    <%= form.date_field :Date %>
  </div>

  <div>
    <%= form.label :Progress, style: "display: block" %>
    <%= form.text_field :Progress %>
  </div>

  <div>
    <%= form.label :Note, style: "display: block" %>
    <%= form.text_field :Note %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity, class:"form-control" %>

<br>

<div>
  <%= link_to "Show this activity", @activity, class:"btn btn-secondary" %> |
  <%= link_to "Back to activities", activities_path, class:"btn btn-secondary" %>
</div>

app/views/activities/index.html.erb
<h1>Activities</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
  <tr>
    <th>Task Name</th>
    <th>Priority</th>
    <th>Date</th>
    <th>Progress</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.TaskName %></td>
    <td><%= activity.Priority %></td>
    <td><%= activity.Date %></td>
    <td><%= activity.Progress %></td>
    <td><%= activity.Note %></td>
	<td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Delete', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path, class:"btn btn-secondary" %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path, class:"btn btn-secondary" %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) ,class:"btn btn-secondary" %> 
  <%= link_to "Back to activities", activities_path, class:"btn btn-secondary" %>
<br><br><br>
  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home/index/">Task Manager</a>


   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      	 <!-- Link tags in ruby style
		home/about is home_about_path
		root is root_path
		can be found from rails routes (look for prefix)


      <li class="nav-item">
         <%= link_to 'About', home_about_path, class:"nav-link active"  %>
        </li>
      	 -->
        

   

         <li class="nav-item">
         <%= link_to 'Tasks', activities_path, class:"nav-link active"  %>
        </li> 

        <!-- Link tags in html style
    	 <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/about">About</a>
        </li>-->
     
      </ul>


      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1> richu </h1>
about

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Task Manager</title>

<style type="text/css">
	@import url(https://fonts.googleapis.com/css?family=Lato:400,300,100,700,900);

h1,
p,
a{
  margin: 0;
  padding: 0;
  font-family: 'Lato';
}

h1 {
  font-size: 2.8em;
  padding: 10px 0;
  font-weight: 800;
}

p {
  font-size: 1.1em;
  font-weight: 100;
  letter-spacing: 5px;
}

.header {
  width: 100%
   height: 100%;
  padding:60px 0;
  text-align: center;
  background: #808080;
  color: white;
}


</style>
  </head>
  <body>
<br><br><br><br><br>
        <section class="header">
    <h1>Task Manager</h1><br>
    <p>Task Management made easier</p>
<br><br><br?
    <%= link_to 'View Tasks', activities_path, class:"btn btn-secondary" %>

</section>

  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Task Manager</title>

    <!-- code copied and pasted from below -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  </head>
  <body>

        <!--creating a link to partial files, those starting with underscore
        equal to tag outputs to the screen,if removed it won't output -->
        <%=render 'home/header' %> <!-- link for partial files--> 
        <div class="container">
        <%= yield %> <!--html page goes here --> 
        </div>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>